name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: lineskin
          POSTGRES_PASSWORD: altel8708
          POSTGRES_DB: lineskin
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov

    - name: Run tests
      env:
        DATABASE_URL: postgresql+asyncpg://lineskin:altel8708@localhost:5432/lineskin
        REDIS_URL: redis://localhost:6379/0
        SECRET_KEY: test-secret-key-1234567890
      run: |
        python -m pytest Нурканат_Алиар_CICD_15/tests/test_auth.py -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: always()

    - name: Build Docker image
      run: |
        docker build -t fastapi-app .
        
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag fastapi-app ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest

